export interface User {
    firstName: string;
    lastName: string;
    email: string;
    mobileNum: string;
    password: string;
    gender: string;
    DOB: Date;
    // id: string;
    // empCode: string;
    // firstName: string;
    // empMIDdlename: string;
    // lastName: string;
    // mobileNum: string;
    //desgID: number;
    // departmentID: number;
    // subDeptID: number;
    // locationID: number;
    // leaveLocnID: number;
    // gradeID: number;
    // plantID: number;
    // companyID: number;
    // divisionID: number;
    // unitCodeID: number;
    // bloodGroupID: number;
    // maritalStatusID: number;
    //gender: string;
    // genderID: number;
    // areaID: number;
    // subAreaID: number;
    // costCenterID: number;
    // subCostCenterID: number;
    // positionCodeID: number;
    // regionID: number;
    //dob: Date; // or Date
    // doa: string;
    // doj: string;
    // dol: string;
    // dtLastWorkingDay: string;
    // councelorID: number;
    // isCouncelor: boolean;
    // councelorID2: number;
    // isCouncelorID2: boolean;
    // emppic: string;
    // isChangePswd: boolean;
    // changepwdDate: string;
    // isRole: boolean;
    // isModerator: boolean;
    // isTopEmpOrgChart: boolean;
    // isGuest: boolean;
    // appDataID: number;
    // status: boolean;
    // archive: boolean;
    // deviceID: string;
    // subUnitID: number;
    // band: number;
    // salesCategory: number;
    // segmentation: number;
    // productCategory: number;
    // customerSegment: number;
    // defaultShiftID: number;
    // isOverTime: number;
    // attEmpCode: number;
    // esi: number;
    // buhead: number;
    // mrfCandidate: number;
    // isConfirmMailSend: boolean;
    // bdmID: number;
    // isAllowCAPEXFORM: boolean;
    // faceRegonisationImagePath: string;
    // faceRegonisationImage: string;
    // isFHPolicy: boolean;
    // refreshToken: string;
    // refreshTokenExpiryTime: string;
    // createdBy: number;
    // createOn: string;
    // modifiedBy: number;
    // modifiedOn: string;
    // userName: string;
    // normalizedUserName: string;
    //email: string;
    // normalizedEmail: string;
    // emailConfirmed: boolean;
    //passwordHash: string;
    // securityStamp: string;
    // concurrencyStamp: string;
    // phoneNumber: string;
    // phoneNumberConfirmed: boolean;
    // twoFactorEnabled: boolean;
    // lockoutEnd: string; // or Date
    // lockoutEnabled: boolean;
    // accessFailedCount: number;
}
